/**
 * libfile.kt
 * Extracts all variables from an OMSI script file (.osc) and saves them in a newly created varlist or stringvarlist.
 *
 * Created by f0xb17 on 04/21/2024.
 * Copyright © 2024 f0xb17. All rights reserved.
 */

package org.foxbit.lib

import java.io.File
import java.io.IOException

/**
 * This class provides all possible functions to automatically generate a varlist or stringvarlist.
 * @param [dir] The file path that contains the .osc files.
 * @param [option] 1 = varlist / 2 = stringvarlist
 */
class File(private val dir: String, private val option: Int) {

    /**
     * This method is used to find all files with the extension .osc at the specified storage point
     * and save them in a list.
     * @param [suffix] The File extension to be searched for. (e.g. .osc)
     * @return a List of Strings, which contains all files with the ending @link[suffix] in a specific folder.
     */
    private fun findFilesInFolder(suffix: String): List<String> {
        val files = File(this.dir).walk()
            .filter { it.isFile && it.name.endsWith(suffix) }
                .toList()
                    .map { it.absolutePath }
        return files
    }

    /**
     * This method is used to save the content of an .osc file into a searchable list of strings.
     * @param [filePath] Represents a file at the specified file path.
     * @return a List of Strings, which contains every line of @link[filePath]
     */
    private fun readFileAsLines(filePath: String): List<String> {
        return File(filePath).readLines().map { it.lowercase() }
    }

    /**
     * This method extracts the desired variables (option: 1 variable / 2 string variables) and returns them as a list.
     * @param [content] Takes a list of strings generated by @link[readFileAsLines]
     * @return a list of Strings, which contains every variable extracted from @link[content]
     */
    private fun extractVariables(content: List<String>): List<String> {
        return when (this.option) {
            1 -> content
                .flatMap { line -> Regex("""\((L\.L|S\.L)\.(\w+)\)""", RegexOption.IGNORE_CASE).findAll(line) }
                .map { it.groupValues[2] }.toSet()
                .map { it }.toList()
            2 -> content
                .flatMap { line -> Regex("""\((S\.\$)\.(\w+)\)""", RegexOption.IGNORE_CASE).findAll(line) }
                .map { it.groupValues[2] }.toSet()
                .map { it }.toList()
            else -> {
                throw IOException()
            }
        }
    }

    /**
     * This method converts the name of an .osc file into the corresponding varlist or stringvarlist
     * by replacing .osc with _varlist.txt or _stringvarlist.txt
     * @param [filePath] Represents an .osc file at a specific file path.
     * @return a converted file that takes the name from @link[filePath] and replaces the file ending with _varlist.txt or _stringvarlist.txt
     */
    private fun convertToVarList(filePath: String): String {
        return when(this.option) {
            1 -> File(File(filePath).parent, File(filePath).nameWithoutExtension + "_varlist.txt").absolutePath
            2 -> File(File(filePath).parent, File(filePath).nameWithoutExtension + "_stringvarlist.txt").absolutePath
            else -> {
                throw IOException()
            }
        }
    }

    /**
     * This method writes the content from @link[extractVariables] to the file converted by @link[convertToVarList].
     */
    fun writer() {
        for(file in this.findFilesInFolder(".osc")) {
            val contents: List<String> = this.extractVariables(this.readFileAsLines(file))
            try {
                File(this.convertToVarList(file)).bufferedWriter().use { writer ->
                    for((index, value) in contents.withIndex()) {
                        writer.write(value)
                        if((contents.size - 1) > index)
                            writer.newLine()
                    }
                }
            } catch(e: Exception) {
                println("Exception while writing the file: $e")
            }
        }
    }
}